### ISSUE TITLE
Nodered crash

### ISSUE THREAD

**Issue by minscof** [vinodsr/node-red-contrib-tuya-smart-device#162]
Nodered crash when some zigbee tuya device (lights) are activated  

These are the messages in the log of nodered :  

nodered  | 8 Mar 23:00:47 - [red] Uncaught Exception:  
nodered  | 8 Mar 23:00:47 - [error] TypeError: Cannot read properties of undefined (reading 'payload')  
nodered  |     at Socket.<anonymous> (/data/node_modules/node-red-contrib-tuya-smart-device/node_modules/tuyapi/index.js:1025:30)  
nodered  |     at Socket.emit (node:events:518:28)  
nodered  |     at UDP.onMessage [as onmessage] (node:dgram:951:8)  

I use node-red-contrib-tuya-smart-device in version 5.3.1

The problem seems to come from tuyaapi.

Could you catch the error to avoid the nodered crash ?
Have you an idea how I can fix the problem ?

Thank you for your help
Minscof

**Comment by xjustbmw** [comment]
also on 5.3.1 (recently updated)

14 Mar 17:31:00 - [error] Error: Timeout waiting for status response from device id: bf17dcd************
    at /home/xjust/.node-red/node_modules/node-red-contrib-tuya-smart-device/node_modules/tuyapi/index.js:460:15
    at Timeout._onTimeout (/home/xjust/.node-red/node_modules/node-red-contrib-tuya-smart-device/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)

node-red crashes

**Comment by vinodsr** [comment]
Thanks  @caitken-com 


Fixed in the latest version 5.3.2 

Let me know if it works.

**Comment by caitken-com** [comment]
Thank you. Have updated, will let you know how it goes! 😊

**Comment by caitken-com** [comment]
Sorry, @vinodsr It's still not fixed, crashing node-red  :(
Unfortunately the stack trace doesn't include your code, so not very helpful. But line 460 within TuyaAPI is the `set()` method. Did your patch wrap all instances/uses of `send()` in try/catches?

```
10 May 11:06:40 - [error] [tuya-smart-device:Rumpus Dimmer] Error from tuyaDevice. shouldTryReconnect = true, error  = "Timeout waitin>
10 May 11:06:40 - [error] [tuya-smart-device:Rumpus Dimmer] This error can be due to invalid DPS values. Please check the dps values i>
10 May 11:06:40 - [red] Uncaught Exception:
10 May 11:06:40 - [error] Error: Timeout waiting for status response from device id: bfeb667fdab659f5f8rxpj
    at /home/chris/.node-red/node_modules/tuyapi/index.js:460:15
    at Timeout._onTimeout (/home/chris/.node-red/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
```

**Comment by Martin12350** [comment]
Same error as @caitken-com here.

**Comment by vinodsr** [comment]
Will look in to this

**Comment by totoCZ** [comment]
Yes, I have this crash on IR blaster. it's a device that doesn't want to return any status.

**Comment by vinodsr** [comment]
@caitken-com  @totoCZ  looks like i had to add error handling in every event method  as they are async and not a promise. ( so cannot add catch to all)

Can you please check now ?

**Comment by Martin12350** [comment]
Thanks for the update will try. Based on your changes all looks promising.
Btw. promise is object return by an async operation. 
You can see even in commect from tuyapi, so what do you mean they are not?

[tuyapi/index.js:115](https://github.com/codetheweb/tuyapi/blob/ffa64c34ff38939e49b8bc51da6935a8a1e6eec0/index.js#L115)
```
  /**
   * Gets a device's current status.
   * Defaults to returning only the value of the first DPS index.
   * @param {Object} [options] Options object
    ...
   * @example
   * // get all available data from device
   * tuya.get({schema: true}).then(data => console.log(data))
   * @returns {Promise<Boolean|undefined|Object>} <----
   * returns boolean if single property is requested, otherwise returns object of results
   */
  async get(options = {}) {
    const payload = {
     ...
```
